//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the total box office: .
        /// </summary>
        public static string addBoxOffice {
            get {
                return ResourceManager.GetString("addBoxOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a New Movie.
        /// </summary>
        public static string addMovieLabel {
            get {
                return ResourceManager.GetString("addMovieLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the movie that you want to add: .
        /// </summary>
        public static string addMovieName {
            get {
                return ResourceManager.GetString("addMovieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the movie release date: .
        /// </summary>
        public static string addReleaseDate {
            get {
                return ResourceManager.GetString("addReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the film studio that produced the movie: .
        /// </summary>
        public static string addStudioName {
            get {
                return ResourceManager.GetString("addStudioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful registration!.
        /// </summary>
        public static string addSuccessMessage {
            get {
                return ResourceManager.GetString("addSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to change the database type? Type | 1 | for Yes or | 2 | for No!.
        /// </summary>
        public static string askDatabase {
            get {
                return ResourceManager.GetString("askDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the following information correct? Type | 1 | for Yes or | 2 | for No: .
        /// </summary>
        public static string askForConfirmation {
            get {
                return ResourceManager.GetString("askForConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing to the main menu....
        /// </summary>
        public static string backMainMenu {
            get {
                return ResourceManager.GetString("backMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Office: .
        /// </summary>
        public static string boxOfficeLabel {
            get {
                return ResourceManager.GetString("boxOfficeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the options below to view the desired movie data: .
        /// </summary>
        public static string chooseMovie {
            get {
                return ResourceManager.GetString("chooseMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the options below to remove:.
        /// </summary>
        public static string chooseMovieRemove {
            get {
                return ResourceManager.GetString("chooseMovieRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the options below to update:.
        /// </summary>
        public static string chooseMovieUpdate {
            get {
                return ResourceManager.GetString("chooseMovieUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure the application database. Choose | 1 | for List , | 2 | for LinkedList, | 3 |  for File or | 4 | for SQL Server. .
        /// </summary>
        public static string databaseChoice {
            get {
                return ResourceManager.GetString("databaseChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid or supported database!.
        /// </summary>
        public static string databaseNotSupported {
            get {
                return ResourceManager.GetString("databaseNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a Movie.
        /// </summary>
        public static string deleteMovieLabel {
            get {
                return ResourceManager.GetString("deleteMovieLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred:.
        /// </summary>
        public static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exitMovieLabel {
            get {
                return ResourceManager.GetString("exitMovieLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List All Movies.
        /// </summary>
        public static string findAllMovieLabel {
            get {
                return ResourceManager.GetString("findAllMovieLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Details about a Movie.
        /// </summary>
        public static string findMovieDetailsLabel {
            get {
                return ResourceManager.GetString("findMovieDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application set up for English!.
        /// </summary>
        public static string languageChoice {
            get {
                return ResourceManager.GetString("languageChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure the application language. Choose | PT | for Portuguese or | EN | for English..
        /// </summary>
        public static string languageChoiceMessage {
            get {
                return ResourceManager.GetString("languageChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid or supported language!.
        /// </summary>
        public static string languageNotSupported {
            get {
                return ResourceManager.GetString("languageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been set up to use the &quot;Database / SQL Server&quot; type as a database..
        /// </summary>
        public static string messageDatabase {
            get {
                return ResourceManager.GetString("messageDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been set up to use the File type as a database..
        /// </summary>
        public static string messageFile {
            get {
                return ResourceManager.GetString("messageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been set up to use the LinkedList type as a database..
        /// </summary>
        public static string messageLinkedList {
            get {
                return ResourceManager.GetString("messageLinkedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been set up to use the List type as a database..
        /// </summary>
        public static string messageList {
            get {
                return ResourceManager.GetString("messageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to get more information about the movie .
        /// </summary>
        public static string moreMovieInfo {
            get {
                return ResourceManager.GetString("moreMovieInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the Box Office or press Enter to keep the old one: .
        /// </summary>
        public static string movieBoxOfficeUpdate {
            get {
                return ResourceManager.GetString("movieBoxOfficeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Details.
        /// </summary>
        public static string movieDetails {
            get {
                return ResourceManager.GetString("movieDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of the Studio or press Enter to keep the old one: .
        /// </summary>
        public static string movieFilmStudioUpdate {
            get {
                return ResourceManager.GetString("movieFilmStudioUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies List.
        /// </summary>
        public static string movieListLabel {
            get {
                return ResourceManager.GetString("movieListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of the Movie or press Enter to keep the old one: .
        /// </summary>
        public static string movieNameUpdate {
            get {
                return ResourceManager.GetString("movieNameUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the Release Date or press Enter to keep the old one: .
        /// </summary>
        public static string movieReleaseDateUpdate {
            get {
                return ResourceManager.GetString("movieReleaseDateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The movie was removed!.
        /// </summary>
        public static string movieRemoved {
            get {
                return ResourceManager.GetString("movieRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no registered movies!.
        /// </summary>
        public static string moviesNotFound {
            get {
                return ResourceManager.GetString("moviesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name, or part of the name of the movie you want to find: .
        /// </summary>
        public static string movieToFind {
            get {
                return ResourceManager.GetString("movieToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name, or part of the name of the movie you want to remove:.
        /// </summary>
        public static string movieToRemove {
            get {
                return ResourceManager.GetString("movieToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name, or part of the name of the movie you want to update:.
        /// </summary>
        public static string movieToUpdate {
            get {
                return ResourceManager.GetString("movieToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The movie has beed updated!.
        /// </summary>
        public static string movieUpdated {
            get {
                return ResourceManager.GetString("movieUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string nameLabel {
            get {
                return ResourceManager.GetString("nameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string noLabel {
            get {
                return ResourceManager.GetString("noLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: .
        /// </summary>
        public static string releaseDateLabel {
            get {
                return ResourceManager.GetString("releaseDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to remove the movie .
        /// </summary>
        public static string removeMovieMessage {
            get {
                return ResourceManager.GetString("removeMovieMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Id .
        /// </summary>
        public static string selectIdMovie {
            get {
                return ResourceManager.GetString("selectIdMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Studio: .
        /// </summary>
        public static string studioLabel {
            get {
                return ResourceManager.GetString("studioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total Box Office was.
        /// </summary>
        public static string textMovieDetailsBoxOffice {
            get {
                return ResourceManager.GetString("textMovieDetailsBoxOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Film Studio.
        /// </summary>
        public static string textMovieDetailsFilmeStudio {
            get {
                return ResourceManager.GetString("textMovieDetailsFilmeStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was released in.
        /// </summary>
        public static string textMovieDetailsRelease {
            get {
                return ResourceManager.GetString("textMovieDetailsRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The movie was released .
        /// </summary>
        public static string textMovieDetailsReleaseCalc {
            get {
                return ResourceManager.GetString("textMovieDetailsReleaseCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago or.
        /// </summary>
        public static string textMovieDetailsReleaseDays {
            get {
                return ResourceManager.GetString("textMovieDetailsReleaseDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string textMovieDetailsReleaseYears {
            get {
                return ResourceManager.GetString("textMovieDetailsReleaseYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was responsible for the production of the movie .
        /// </summary>
        public static string textMovieDetailsReponsable {
            get {
                return ResourceManager.GetString("textMovieDetailsReponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Movie Information.
        /// </summary>
        public static string updateMovieLabel {
            get {
                return ResourceManager.GetString("updateMovieLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to update the movie.
        /// </summary>
        public static string updateMovieMessage {
            get {
                return ResourceManager.GetString("updateMovieMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        public static string whatToDo {
            get {
                return ResourceManager.GetString("whatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yesLabel {
            get {
                return ResourceManager.GetString("yesLabel", resourceCulture);
            }
        }
    }
}
