name: Awesome Tomatoes ASPNET AT

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github"
      - "**/README.md"
      - "**/project-de-bloco/**"
      - "**/fundamentos-csharp/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore fundamentos-aspnet/AT/solution/

      - name: Build
        run: dotnet build -c release --no-restore fundamentos-aspnet/AT/solution
#      - name: Upload a Build Artifact
#        uses: actions/upload-artifact@v2.2.2
#        with:
#          name: GitHubActionsAwesomeTomatoesASPNET
#          path: fundamentos-aspnet/TP03/solution/*.*
